use dbs_22_tst;
insert into executives (name) values ('gpbgteuksnmq');
insert into executives (name) values ('ikcazkqu');
insert into executives (name) values ('achualmqir');
insert into executives (name) values ('yekblixvptgbi');
insert into executives (name) values ('gicqlkmqktqvjq');
insert into executives (name) values ('ymmlfgbbglo');
insert into executives (name) values ('vkjces');
insert into executives (name) values ('sleeh');
insert into executives (name) values ('ebiqpaagvfxbfb');
insert into executives (name) values ('yvjtdi');
insert into executives (name) values ('nzvjbmgy');
insert into executives (name) values ('hbpmm');
insert into executives (name) values ('zwrmsqzyoxblo');
insert into executives (name) values ('njjfppdfd');
insert into executives (name) values ('kmltn');
insert into executives (name) values ('ddfidvdo');
insert into executives (name) values ('xclekfrusvqxfa');
insert into executives (name) values ('pggcuzujmcld');
insert into executives (name) values ('ryyrdktngvlhb');
insert into executives (name) values ('rvqbpkazi');
insert into executives (name) values ('brknvkfdnu');
insert into executives (name) values ('pkrvms');
insert into executives (name) values ('yxhckqq');
insert into executives (name) values ('admfwbhcnq');
insert into executives (name) values ('rakzqw');
insert into program (name,department) values ('dfbhhxd','uwcrcacnr');
insert into program (name,department) values ('tlwhzkpsg','yxcpzoqngtscai');
insert into program (name,department) values ('afeeo','qhbsutk');
insert into program (name,department) values ('uwblp','imphml');
insert into program (name,department) values ('jriltmwlx','asnqvzwpss');
insert into program (name,department) values ('pgyygjiwfixywf','lakbrugngo');
insert into program (name,department) values ('wtaepquk','hdjlhsflqo');
insert into program (name,department) values ('ynhnxyj','awyraffvy');
insert into program (name,department) values ('aadlckqhvwtba','knjpbtzflho');
insert into program (name,department) values ('sqzewhoynhbwj','eavbm');
insert into program (name,department) values ('mwerwxfuoxk','rngcmmqsfsv');
insert into program (name,department) values ('lvztmqdf','tstcrma');
insert into program (name,department) values ('lyudbb','imvikjeafdxor');
insert into program (name,department) values ('lopjqhod','aampzhgzfozzf');
insert into program (name,department) values ('uqujk','nydlfkvyw');
insert into program (name,department) values ('zybjbt','yebidvrbv');
insert into program (name,department) values ('rrpoendjgm','gvwuupuj');
insert into program (name,department) values ('xisptzfnytwlv','vdohpnqknk');
insert into program (name,department) values ('kqksqvfsszkca','bxqglgwker');
insert into program (name,department) values ('aocdglqmrdoi','hmcdtsf');
insert into program (name,department) values ('hkymnhvusq','oupxmctaxfxlh');
insert into program (name,department) values ('enzbzsukhdg','cefwurifya');
insert into program (name,department) values ('gnqmmj','ibliqsd');
insert into program (name,department) values ('lcyifdgchi','eokdgkestohxvv');
insert into program (name,department) values ('czrkebwtosaxt','iigwga');
insert into program (name,department) values ('fndqfjuqp','yxymngjqygssn');
insert into program (name,department) values ('gqetkdcjlphi','tqpiho');
insert into program (name,department) values ('clwqqyswloi','mdsow');
insert into program (name,department) values ('bywhlaabju','tsixrzkitgx');
insert into program (name,department) values ('vfsntzlaqirij','nacyvyfg');
insert into organisation (name, short_name, postal_code, street, city) values ('oantpwu','mejg',14608,'lwzooon','yxwbynrz');
insert into organisation (name, short_name, postal_code, street, city) values ('uzyptvdrfjb','dbbsfp',16151,'apjurrxjb','lxwqjxvcmpmp');
insert into organisation (name, short_name, postal_code, street, city) values ('cqdkkdgtif','tzk',18284,'stmwfpzm','bvgcoddf');
insert into organisation (name, short_name, postal_code, street, city) values ('aujhylsw','gcv',19683,'uxiufksdwzgi','kraiyccbp');
insert into organisation (name, short_name, postal_code, street, city) values ('xqghytkynkdfai','vafv',14783,'rmydcebvxmj','awxemh');
insert into organisation (name, short_name, postal_code, street, city) values ('fbsgznw','vkxc',18855,'jqhrpjn','lsdbcngahhtg');
insert into organisation (name, short_name, postal_code, street, city) values ('cevtgwaewhtssg','fgmro',18398,'sdutrzcgt','ycumsvi');
insert into organisation (name, short_name, postal_code, street, city) values ('hxkbeanmyzzht','imfi',18865,'mbdnnly','ybijbry');
insert into organisation (name, short_name, postal_code, street, city) values ('mlbmhfm','kvpq',15785,'xnnsiht','pysvnibnypy');
insert into organisation (name, short_name, postal_code, street, city) values ('ykpivkmvmb','kwe',14723,'whvbnasrpooxbe','adtapfpcz');
insert into organisation (name, short_name, postal_code, street, city) values ('acgufaaci','tmi',13884,'ywiumipyrv','hgzfrz');
insert into organisation (name, short_name, postal_code, street, city) values ('epnyomuh','joj',16759,'fmzaezg','hvksk');
insert into organisation (name, short_name, postal_code, street, city) values ('gqiej','hws',17718,'tvmmfaxdcberd','cnxkcyepcppdtk');
insert into organisation (name, short_name, postal_code, street, city) values ('osjemfeph','fhto',15428,'eqqaztovha','jsyaooquvocam');
insert into organisation (name, short_name, postal_code, street, city) values ('ssesvfgudzjjgh','jvat',19006,'aggqlcnopty','dxvlmxpcrzlkbq');
insert into organisation (name, short_name, postal_code, street, city) values ('ehdvtzxlljr','cupm',17294,'pnaptxwziccra','jxfghbkggqai');
insert into organisation (name, short_name, postal_code, street, city) values ('zkxkwwjz','shvfq',19551,'ilpmojyf','khswlsfg');
insert into organisation (name, short_name, postal_code, street, city) values ('tkcivhztbrxjnv','hymbab',19065,'ntrszoko','htdhzyfltkysy');
insert into organisation (name, short_name, postal_code, street, city) values ('dfydqvv','uckc',18070,'viafaujzkxsynf','egkpshzwrkd');
insert into organisation (name, short_name, postal_code, street, city) values ('yvhcb','hktx',17539,'oyoibyllj','mtifsbi');
insert into organisation (name, short_name, postal_code, street, city) values ('iqcuriymenyaf','xrnow',10920,'tionepcnggfy','lxykfdngr');
insert into organisation (name, short_name, postal_code, street, city) values ('xyjmauzwbr','mfcufa',15593,'pyosdbpftxado','qvhpbehiesv');
insert into organisation (name, short_name, postal_code, street, city) values ('usdzp','osjp',19826,'yihsqltyzzn','jhihcwmuqiv');
insert into organisation (name, short_name, postal_code, street, city) values ('hvhkvxy','kccbc',16291,'bcjkwg','xkmgkwzu');
insert into organisation (name, short_name, postal_code, street, city) values ('lrvmcgikco','jfr',15735,'buymgiks','gjumkqhjkq');
insert into organisation (name, short_name, postal_code, street, city) values ('mctgy','yiuxd',16467,'cmjvpnoexub','izkdsq');
insert into organisation (name, short_name, postal_code, street, city) values ('mekwsuxdmugy','nkxy',14390,'trvuysylr','qlkolrnvrslr');
insert into organisation (name, short_name, postal_code, street, city) values ('njvlatagehf','fjefps',12983,'hihwtf','udjvfvrfzqcwtb');
insert into organisation (name, short_name, postal_code, street, city) values ('xiatlou','pizqp',15283,'lmhccigzhrxw','xeqxagom');
insert into organisation (name, short_name, postal_code, street, city) values ('tflyd','aeyzm',11359,'ahciauwoeawv','yxdltafpypot');
insert into company (capital,org_id) values (719226,18);
insert into company (capital,org_id) values (747367,17);
insert into company (capital,org_id) values (980087,27);
insert into company (capital,org_id) values (120388,19);
insert into company (capital,org_id) values (798491,5);
insert into company (capital,org_id) values (377068,25);
insert into company (capital,org_id) values (161023,22);
insert into company (capital,org_id) values (971325,4);
insert into company (capital,org_id) values (963948,15);
insert into company (capital,org_id) values (609380,12);
insert into university (budget,org_id) values (867304,10);
insert into university (budget,org_id) values (948608,13);
insert into university (budget,org_id) values (477875,7);
insert into university (budget,org_id) values (616436,20);
insert into university (budget,org_id) values (895483,11);
insert into university (budget,org_id) values (267391,8);
insert into university (budget,org_id) values (542126,26);
insert into university (budget,org_id) values (305455,14);
insert into university (budget,org_id) values (294511,28);
insert into university (budget,org_id) values (449548,24);
insert into research_center (budget,private,org_id) values (491622,110587,29);
insert into research_center (budget,private,org_id) values (966282,636559,16);
insert into research_center (budget,private,org_id) values (386502,531125,9);
insert into research_center (budget,private,org_id) values (997441,638042,6);
insert into research_center (budget,private,org_id) values (932720,272355,1);
insert into research_center (budget,private,org_id) values (376542,141334,3);
insert into research_center (budget,private,org_id) values (557293,145204,2);
insert into research_center (budget,private,org_id) values (550220,561356,30);
insert into research_center (budget,private,org_id) values (640771,849364,21);
insert into research_center (budget,private,org_id) values (671675,392077,23);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('tiavqdpz','kzpnpcz','2015-10-23','female',25);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('bnqoydb','lhifdg','2017-05-16','female',24);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('ykfyknysp','vlxbzx','2010-12-01','male',13);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('zpzkwqt','gtzau','2010-07-07','male',24);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('rnosym','wfmyfxk','2000-04-16','male',9);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('apvtoaum','bwutvmz','2021-12-13','female',5);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('skqrxwz','alhynjj','2002-04-21','female',22);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('bciznsemz','muaxtzloc','2017-08-16','female',28);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('iofrpv','nbsxovg','2011-08-20','female',25);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('uvlpf','vrybnmpp','2015-06-27','male',23);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('cufwrr','guevoi','2013-04-26','male',11);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('unnkynva','ulneuvdal','2021-12-23','male',16);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('xitzxoo','qdywcpys','2007-12-07','male',29);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('fwatp','wenpwh','2021-02-26','female',19);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('jkooan','qghkscg','2015-01-16','male',13);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('qdnkjph','wypqxsivr','2016-12-16','male',21);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('xyfqhluhv','eqpkv','2016-03-06','male',30);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('jjikbg','zcrlbagbp','2013-09-16','male',25);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('bqsvv','fvpijmsqq','2003-09-04','female',15);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('lgnkrvc','isxjtc','2021-02-14','female',29);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('gdoetl','nymipyew','2010-03-15','male',23);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('vlhxtuxn','beoac','2021-07-26','male',12);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('oyitop','mmpmlm','2003-12-26','female',1);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('mrqldim','tcdgv','2021-01-25','male',7);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('lqxlcyc','tcubs','2011-10-11','male',11);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('lxcslcft','fsvfajrua','2009-01-02','female',5);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('zpziv','zkjkoqvf','2008-01-19','female',21);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('ckdrqrk','rfscg','2016-09-25','female',16);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('odbsz','upfiyc','2000-06-10','female',28);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('aizubc','megrmdj','2013-07-22','female',3);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('caxzft','yrbqpiq','2007-08-26','female',11);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('rcspbr','eioypkdt','2012-08-17','female',21);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('cmstwyo','fzoqbt','2002-06-22','male',28);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('lkjwyb','tubeezed','2016-07-14','male',19);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('cnbaha','hvyxscij','2001-02-24','female',13);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('bwknlditg','hscjhwo','2001-07-07','male',4);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('pkmdfyott','hwfvyn','2018-05-23','female',4);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('udaji','ziyiomaou','2015-03-27','male',26);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('kzfiad','epqpends','2021-08-21','female',6);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('qdujppwfg','velxmqhyd','2002-01-11','male',26);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('rmzmq','olltvggh','2015-12-08','female',12);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('jvuaunf','jtticzvp','2013-03-09','female',26);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('jsmuzkdex','omway','2007-03-24','female',16);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('zygtqek','qpuye','2005-10-09','male',12);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('ufcnre','fojehk','2004-06-08','male',9);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('irfoezb','ocgctsgxq','2006-05-26','male',26);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('eapssmw','uevbzh','2018-04-22','male',19);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('myadt','bfxyq','2021-03-14','male',24);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('jeuuum','xctklvx','2017-06-17','female',16);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('skeuv','towpvrkx','2011-09-25','female',1);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('nzzyh','sqjtbt','2013-10-20','male',4);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('fuqprghfe','ilnun','2021-04-10','male',24);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('jwpqiz','xhwrc','2003-02-15','female',2);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('tibduhkd','gmkrfnsnb','2000-10-10','female',14);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('erqkpcqpi','lrnej','2003-09-26','male',8);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('wveoejk','lhnvq','2007-07-27','female',12);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('djqvc','pfzpppath','2015-04-11','male',4);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('kqdiwosp','kesnwo','2001-01-23','male',6);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('eotln','ozbgwllhg','2014-12-08','male',23);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('ddatofh','deooxec','2020-04-26','male',4);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('vwwqkqgif','tbgqfan','2002-02-25','female',10);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('lkblp','xwlipa','2008-08-27','female',7);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('tkivzf','zgwsjqy','2007-12-10','male',19);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('njmfm','yzixjhls','2012-07-18','female',9);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('axoupibvi','sapybyiva','2005-03-24','female',26);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('mxznl','ovgfk','2007-03-01','female',20);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('vcqako','vmfnwj','2006-11-03','female',29);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('jyrcyigh','oesvp','2015-07-13','female',17);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('lpoqtjwn','zrckgk','2002-08-10','male',15);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('dzlgiheka','skjszuxt','2018-06-19','female',16);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('pewbgn','suvvuvwm','2013-02-03','male',20);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('wqdiigv','favuumk','2007-03-14','female',22);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('zyjanrd','idfeomfcq','2014-02-15','male',11);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('nebzzypcg','bkmmcufr','2010-02-07','male',5);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('ucgcqoro','dzbtbe','2007-04-27','female',3);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('occkewphl','nebjwcizi','2018-06-24','female',5);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('lkcqb','gevqpcf','2003-10-09','female',15);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('kbzrxr','hdaulbb','2007-07-15','male',18);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('qrkxc','dvyyqb','2001-11-05','female',14);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('mneqnexo','dsvyhb','2019-09-20','male',25);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('cphyjqom','bnpoqm','2018-05-28','female',13);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('ojsowsiuz','gzfimnta','2003-05-13','female',25);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('kleanqv','zzjjyfr','2021-01-01','female',20);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('eojkjtrhf','xygfhgfmy','2015-04-15','female',8);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('lubsxnjik','tijvigfwo','2011-05-01','female',26);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('aazez','cxqhj','2007-03-10','male',22);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('rhajqkt','lexphhgmi','2008-02-11','female',14);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('inygnly','yebkyketw','2009-09-11','female',17);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('okzvndbjn','vpopg','2004-08-12','female',24);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('armdu','ctfpdwi','2021-05-06','female',16);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('ycfkyq','mwguui','2015-05-26','male',3);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('tzayfujd','ibpdq','2005-07-02','male',25);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('jcekkdgkx','ruupzxdz','2007-07-16','male',12);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('kyibgb','netwz','2008-07-24','male',27);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('ptegvnonm','baabmxth','2003-04-17','female',8);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('hbemwg','ppiruwk','2018-07-19','male',6);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('xchgqszk','rarwxk','2001-08-14','female',7);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('oohmiil','knbikmnh','2017-08-24','female',27);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('blhqw','kjvkypqa','2002-10-18','male',9);
insert into researcher (f_name,l_name,birthdate,gender,works_for) values ('bhmcnyvf','apxzympe','2018-07-06','female',11);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (948069,'csistkbvl','2019-02-26','1999-01-01','blah blah',8,20,66,68,71,20);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (173352,'uecieievtmnjdb','2020-03-08','1999-01-01','blah blah',6,17,26,49,10,10);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (940545,'klbent','2020-09-14','1999-01-01','blah blah',7,4,99,100,77,28);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (493110,'wkteawxl','2020-09-19','1999-01-01','blah blah',17,25,10,16,2,4);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (956746,'jjrftmv','2018-02-07','1999-01-01','blah blah',24,17,99,94,91,4);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (940773,'yjkxdhbztkd','2021-04-14','1999-01-01','blah blah',7,20,86,2,4,5);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (636948,'ioonmknzeo','2018-01-17','1999-01-01','blah blah',6,9,86,65,90,27);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (316259,'dfysidbkszjj','2020-07-02','1999-01-01','blah blah',17,9,32,34,50,30);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (328724,'hwdkdtw','2019-11-10','1999-01-01','blah blah',18,17,14,18,75,23);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (477730,'epoqquvdqg','2018-04-11','1999-01-01','blah blah',5,29,5,16,44,18);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (118535,'gbylbjtz','2021-08-07','1999-01-01','blah blah',22,10,17,21,31,17);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (115154,'yaodkelldfo','2020-04-22','1999-01-01','blah blah',22,16,90,24,94,30);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (531155,'imbxag','2020-02-26','1999-01-01','blah blah',11,17,46,62,41,30);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (186689,'qqkojoup','2019-07-13','1999-01-01','blah blah',25,5,33,17,13,9);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (271343,'fbfws','2018-08-22','1999-01-01','blah blah',25,26,37,80,40,17);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (737946,'rvqywh','2021-09-16','1999-01-01','blah blah',2,10,15,46,99,27);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (417552,'qijpzbuldr','2021-08-08','1999-01-01','blah blah',14,19,95,66,22,2);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (394948,'tnpokdfbmezqdp','2020-12-21','1999-01-01','blah blah',7,1,64,74,57,4);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (253310,'lduyqpsdjgcam','2018-07-26','1999-01-01','blah blah',3,16,75,33,71,1);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (607837,'igdcdfdvrfqef','2019-04-09','1999-01-01','blah blah',4,29,7,48,44,28);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (355991,'lfurqs','2020-03-08','1999-01-01','blah blah',8,30,93,77,16,13);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (230860,'smbkjmjrbghy','2018-04-11','1999-01-01','blah blah',21,1,53,3,96,16);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (496633,'irjofuhqesz','2019-11-15','1999-01-01','blah blah',6,17,27,67,23,8);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (762425,'axeqphqkdlo','2018-11-26','1999-01-01','blah blah',21,20,61,37,60,20);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (603536,'ouvhanjir','2021-08-13','1999-01-01','blah blah',5,11,44,65,92,8);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (837767,'kmoiiinbqeog','2021-01-07','1999-01-01','blah blah',19,29,49,80,17,13);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (564160,'qyigdm','2019-01-01','1999-01-01','blah blah',25,24,99,27,62,1);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (509653,'uqlicqza','2019-12-21','1999-01-01','blah blah',20,21,87,91,31,8);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (338749,'txooqfp','2018-04-25','1999-01-01','blah blah',1,10,16,68,65,4);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (505039,'ukynlnlkrkux','2021-02-01','1999-01-01','blah blah',16,10,12,11,22,12);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (937084,'tibrjnx','2012-12-10','2013-06-14','blah blah',5,4,98,98,50,13);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (581507,'hnfcsw','2019-02-06','2020-08-09','blah blah',15,9,46,92,85,21);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (529595,'hynjrtrfv','2006-06-01','2008-08-06','blah blah',18,2,50,52,58,25);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (557386,'sqpbte','2011-05-11','2014-11-25','blah blah',20,4,21,54,44,8);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (535760,'xcbjzvvow','2018-06-07','2019-12-06','blah blah',24,15,63,72,35,16);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (473991,'ziavbtsnvzu','2000-09-06','2001-01-17','blah blah',1,27,68,34,8,10);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (163781,'caslzszrqxpruf','2009-01-09','2010-07-25','blah blah',15,9,63,65,25,11);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (923374,'ilydpipkvaixz','2013-10-10','2014-09-06','blah blah',7,13,76,87,55,27);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (743053,'ijntw','2006-11-20','2008-12-09','blah blah',10,16,31,69,42,21);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (248081,'alakoyjcl','2006-11-18','2008-12-24','blah blah',8,12,26,88,78,6);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (965868,'sxtfdqiieakuk','2020-05-26','2021-03-19','blah blah',6,16,63,73,2,1);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (991598,'glbgui','2012-08-03','2016-12-04','blah blah',1,14,94,64,7,14);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (593045,'ycwngsdwmad','2003-12-21','2006-12-15','blah blah',10,10,6,96,97,10);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (940403,'qtydxzb','2001-11-08','2002-10-26','blah blah',8,19,93,97,96,9);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (599485,'viypd','2012-03-06','2015-09-05','blah blah',25,8,96,40,65,4);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (220518,'imctidhtqfu','2019-01-19','2021-02-01','blah blah',14,15,90,17,57,30);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (316714,'cmqwdbvuvfg','2014-09-20','2018-05-14','blah blah',19,11,50,75,91,29);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (520922,'ubzwpbiiypqb','2006-11-02','2007-04-16','blah blah',23,6,63,39,71,29);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (948520,'ideofrwt','2008-06-27','2012-02-04','blah blah',19,1,88,35,97,14);
insert into project (amount,title,start,finish,summary,managed_by_exec,sponsorship,sc_head,researcher_0,evaluates,managed_by_org) values (157872,'mwltvnqkmgf','2008-02-04','2011-03-25','blah blah',6,9,61,43,30,29);
insert into sc_fields (name,project_id) values ('med',18);
insert into sc_fields (name,project_id) values ('mth',47);
insert into sc_fields (name,project_id) values ('med',28);
insert into sc_fields (name,project_id) values ('bio',6);
insert into sc_fields (name,project_id) values ('phy',15);
insert into sc_fields (name,project_id) values ('bio',8);
insert into sc_fields (name,project_id) values ('phy',43);
insert into sc_fields (name,project_id) values ('chm',32);
insert into sc_fields (name,project_id) values ('mth',31);
insert into sc_fields (name,project_id) values ('chm',44);
insert into sc_fields (name,project_id) values ('cs',20);
insert into sc_fields (name,project_id) values ('cs',18);
insert into sc_fields (name,project_id) values ('bio',23);
insert into sc_fields (name,project_id) values ('chm',10);
insert into sc_fields (name,project_id) values ('med',44);
insert into sc_fields (name,project_id) values ('cs',40);
insert into sc_fields (name,project_id) values ('cs',5);
insert into sc_fields (name,project_id) values ('cs',8);
insert into sc_fields (name,project_id) values ('bio',42);
insert into sc_fields (name,project_id) values ('cs',12);
insert into sc_fields (name,project_id) values ('phy',48);
insert into sc_fields (name,project_id) values ('med',1);
insert into sc_fields (name,project_id) values ('mth',48);
insert into sc_fields (name,project_id) values ('med',29);
insert into sc_fields (name,project_id) values ('bio',45);
insert into sc_fields (name,project_id) values ('chm',50);
insert into sc_fields (name,project_id) values ('mth',20);
insert into sc_fields (name,project_id) values ('cs',42);
insert into sc_fields (name,project_id) values ('med',46);
insert into sc_fields (name,project_id) values ('cs',43);
insert into sc_fields (name,project_id) values ('chm',5);
insert into sc_fields (name,project_id) values ('mth',6);
insert into sc_fields (name,project_id) values ('mth',30);
insert into sc_fields (name,project_id) values ('chm',4);
insert into sc_fields (name,project_id) values ('med',1);
insert into sc_fields (name,project_id) values ('bio',31);
insert into sc_fields (name,project_id) values ('cs',30);
insert into sc_fields (name,project_id) values ('bio',38);
insert into sc_fields (name,project_id) values ('med',46);
insert into sc_fields (name,project_id) values ('med',50);
insert into sc_fields (name,project_id) values ('mth',46);
insert into sc_fields (name,project_id) values ('med',9);
insert into sc_fields (name,project_id) values ('mth',46);
insert into sc_fields (name,project_id) values ('med',39);
insert into sc_fields (name,project_id) values ('cs',9);
insert into sc_fields (name,project_id) values ('cs',43);
insert into sc_fields (name,project_id) values ('bio',16);
insert into sc_fields (name,project_id) values ('cs',18);
insert into sc_fields (name,project_id) values ('cs',39);
insert into sc_fields (name,project_id) values ('phy',27);
insert into sc_fields (name,project_id) values ('med',43);
insert into sc_fields (name,project_id) values ('phy',20);
insert into sc_fields (name,project_id) values ('mth',45);
insert into sc_fields (name,project_id) values ('mth',22);
insert into sc_fields (name,project_id) values ('med',16);
insert into sc_fields (name,project_id) values ('chm',28);
insert into sc_fields (name,project_id) values ('bio',15);
insert into sc_fields (name,project_id) values ('chm',37);
insert into sc_fields (name,project_id) values ('med',5);
insert into sc_fields (name,project_id) values ('chm',17);
insert into sc_fields (name,project_id) values ('med',29);
insert into sc_fields (name,project_id) values ('bio',34);
insert into sc_fields (name,project_id) values ('mth',48);
insert into sc_fields (name,project_id) values ('cs',21);
insert into sc_fields (name,project_id) values ('chm',28);
insert into sc_fields (name,project_id) values ('chm',17);
insert into sc_fields (name,project_id) values ('mth',8);
insert into sc_fields (name,project_id) values ('phy',30);
insert into sc_fields (name,project_id) values ('cs',47);
insert into sc_fields (name,project_id) values ('bio',4);
insert into sc_fields (name,project_id) values ('bio',47);
insert into sc_fields (name,project_id) values ('med',16);
insert into sc_fields (name,project_id) values ('chm',13);
insert into sc_fields (name,project_id) values ('bio',15);
insert into sc_fields (name,project_id) values ('mth',38);
insert into sc_fields (name,project_id) values ('phy',18);
insert into sc_fields (name,project_id) values ('bio',38);
insert into sc_fields (name,project_id) values ('chm',46);
insert into sc_fields (name,project_id) values ('mth',19);
insert into sc_fields (name,project_id) values ('cs',25);
insert into sc_fields (name,project_id) values ('phy',43);
insert into sc_fields (name,project_id) values ('chm',46);
insert into sc_fields (name,project_id) values ('bio',42);
insert into sc_fields (name,project_id) values ('med',44);
insert into sc_fields (name,project_id) values ('med',7);
insert into sc_fields (name,project_id) values ('bio',37);
insert into sc_fields (name,project_id) values ('phy',41);
insert into sc_fields (name,project_id) values ('bio',10);
insert into sc_fields (name,project_id) values ('bio',49);
insert into sc_fields (name,project_id) values ('chm',33);
insert into sc_fields (name,project_id) values ('med',14);
insert into sc_fields (name,project_id) values ('phy',33);
insert into sc_fields (name,project_id) values ('chm',25);
insert into sc_fields (name,project_id) values ('chm',3);
insert into sc_fields (name,project_id) values ('bio',42);
insert into sc_fields (name,project_id) values ('phy',48);
insert into sc_fields (name,project_id) values ('bio',43);
insert into sc_fields (name,project_id) values ('bio',30);
insert into sc_fields (name,project_id) values ('cs',10);
insert into sc_fields (name,project_id) values ('bio',23);
insert into deliverables (title,summary,project_id,delivered) values ('mfilrlnocduh','summary_text',28,'2019-12-23');
insert into deliverables (title,summary,project_id,delivered) values ('ovhallealykl','summary_text',42,'2012-10-02');
insert into deliverables (title,summary,project_id,delivered) values ('sakxsfizx','summary_text',8,'2020-09-10');
insert into deliverables (title,summary,project_id,delivered) values ('rzdvuhx','summary_text',1,'2019-12-25');
insert into deliverables (title,summary,project_id,delivered) values ('efjvncmjtoft','summary_text',5,'2018-06-02');
insert into deliverables (title,summary,project_id,delivered) values ('upkpbirstr','summary_text',40,'2006-11-24');
insert into deliverables (title,summary,project_id,delivered) values ('bfokbp','summary_text',50,'2008-03-22');
insert into deliverables (title,summary,project_id,delivered) values ('kqjrmbuwtrsx','summary_text',32,'2019-04-26');
insert into deliverables (title,summary,project_id,delivered) values ('eroukdhp','summary_text',23,'2019-12-02');
insert into deliverables (title,summary,project_id,delivered) values ('luwsytptpv','summary_text',37,'2009-08-08');
insert into deliverables (title,summary,project_id,delivered) values ('zvmkr','summary_text',50,'2008-10-27');
insert into deliverables (title,summary,project_id,delivered) values ('tkjrbq','summary_text',1,'2019-11-28');
insert into deliverables (title,summary,project_id,delivered) values ('oaqpc','summary_text',18,'2020-12-27');
insert into deliverables (title,summary,project_id,delivered) values ('jdohgywyqb','summary_text',17,'2021-09-10');
insert into deliverables (title,summary,project_id,delivered) values ('gxipwrmivaxq','summary_text',25,'2021-12-18');
insert into deliverables (title,summary,project_id,delivered) values ('hpjesmxzezo','summary_text',18,'2020-12-27');
insert into deliverables (title,summary,project_id,delivered) values ('vuwtjj','summary_text',47,'2014-10-18');
insert into deliverables (title,summary,project_id,delivered) values ('kefdebfkeci','summary_text',41,'2020-09-14');
insert into deliverables (title,summary,project_id,delivered) values ('zfbtmoaolqgds','summary_text',25,'2021-11-22');
insert into deliverables (title,summary,project_id,delivered) values ('glzljpf','summary_text',37,'2009-09-14');
insert into deliverables (title,summary,project_id,delivered) values ('zalup','summary_text',27,'2019-03-06');
insert into deliverables (title,summary,project_id,delivered) values ('vpsnvrpvrlim','summary_text',36,'2000-12-01');
insert into deliverables (title,summary,project_id,delivered) values ('jaglzpcosfsazn','summary_text',31,'2012-12-25');
insert into deliverables (title,summary,project_id,delivered) values ('pfiwire','summary_text',18,'2020-12-25');
insert into deliverables (title,summary,project_id,delivered) values ('oebniwpburwe','summary_text',12,'2020-08-20');
insert into deliverables (title,summary,project_id,delivered) values ('hjncqhbui','summary_text',43,'2003-12-28');
insert into deliverables (title,summary,project_id,delivered) values ('yawwqil','summary_text',28,'2019-12-21');
insert into deliverables (title,summary,project_id,delivered) values ('vtlsvuz','summary_text',29,'2018-10-01');
insert into deliverables (title,summary,project_id,delivered) values ('logegvopdgrd','summary_text',20,'2019-05-07');
insert into deliverables (title,summary,project_id,delivered) values ('ugumqkdxhjf','summary_text',27,'2019-08-25');
insert into evaluations (grade, eval_date, project_id) values (3,'2019-03-25',1);
insert into evaluations (grade, eval_date, project_id) values (9,'2020-08-17',2);
insert into evaluations (grade, eval_date, project_id) values (10,'2020-10-17',3);
insert into evaluations (grade, eval_date, project_id) values (4,'2020-10-05',4);
insert into evaluations (grade, eval_date, project_id) values (10,'2018-04-11',5);
insert into evaluations (grade, eval_date, project_id) values (4,'2021-10-24',6);
insert into evaluations (grade, eval_date, project_id) values (6,'2018-11-22',7);
insert into evaluations (grade, eval_date, project_id) values (4,'2020-12-03',8);
insert into evaluations (grade, eval_date, project_id) values (3,'2019-11-18',9);
insert into evaluations (grade, eval_date, project_id) values (6,'2018-05-08',10);
insert into evaluations (grade, eval_date, project_id) values (9,'2021-08-22',11);
insert into evaluations (grade, eval_date, project_id) values (6,'2020-08-19',12);
insert into evaluations (grade, eval_date, project_id) values (7,'2020-12-24',13);
insert into evaluations (grade, eval_date, project_id) values (8,'2019-08-25',14);
insert into evaluations (grade, eval_date, project_id) values (8,'2018-10-05',15);
insert into evaluations (grade, eval_date, project_id) values (8,'2021-12-08',16);
insert into evaluations (grade, eval_date, project_id) values (10,'2021-11-10',17);
insert into evaluations (grade, eval_date, project_id) values (7,'2020-12-22',18);
insert into evaluations (grade, eval_date, project_id) values (4,'2018-08-02',19);
insert into evaluations (grade, eval_date, project_id) values (6,'2019-04-26',20);
insert into evaluations (grade, eval_date, project_id) values (5,'2020-06-10',21);
insert into evaluations (grade, eval_date, project_id) values (9,'2018-04-12',22);
insert into evaluations (grade, eval_date, project_id) values (10,'2019-11-16',23);
insert into evaluations (grade, eval_date, project_id) values (10,'2018-12-11',24);
insert into evaluations (grade, eval_date, project_id) values (4,'2021-08-21',25);
insert into evaluations (grade, eval_date, project_id) values (4,'2021-12-19',26);
insert into evaluations (grade, eval_date, project_id) values (2,'2019-01-17',27);
insert into evaluations (grade, eval_date, project_id) values (3,'2019-12-27',28);
insert into evaluations (grade, eval_date, project_id) values (5,'2018-09-12',29);
insert into evaluations (grade, eval_date, project_id) values (2,'2021-11-22',30);
insert into evaluations (grade, eval_date, project_id) values (2,'2012-12-27',31);
insert into evaluations (grade, eval_date, project_id) values (6,'2019-08-17',32);
insert into evaluations (grade, eval_date, project_id) values (4,'2006-12-24',33);
insert into evaluations (grade, eval_date, project_id) values (4,'2011-10-02',34);
insert into evaluations (grade, eval_date, project_id) values (3,'2018-10-22',35);
insert into evaluations (grade, eval_date, project_id) values (6,'2000-12-22',36);
insert into evaluations (grade, eval_date, project_id) values (10,'2009-12-20',37);
insert into evaluations (grade, eval_date, project_id) values (3,'2013-11-28',38);
insert into evaluations (grade, eval_date, project_id) values (5,'2006-12-27',39);
insert into evaluations (grade, eval_date, project_id) values (2,'2006-11-26',40);
insert into evaluations (grade, eval_date, project_id) values (3,'2020-06-24',41);
insert into evaluations (grade, eval_date, project_id) values (8,'2012-09-14',42);
insert into evaluations (grade, eval_date, project_id) values (1,'2003-12-22',43);
insert into evaluations (grade, eval_date, project_id) values (5,'2001-11-18',44);
insert into evaluations (grade, eval_date, project_id) values (0,'2012-10-05',45);
insert into evaluations (grade, eval_date, project_id) values (2,'2019-09-17',46);
insert into evaluations (grade, eval_date, project_id) values (4,'2014-10-16',47);
insert into evaluations (grade, eval_date, project_id) values (5,'2006-12-12',48);
insert into evaluations (grade, eval_date, project_id) values (6,'2008-08-27',49);
insert into evaluations (grade, eval_date, project_id) values (9,'2008-11-21',50);
insert into researchers_projects (researcher_id,project_id) values (98,1);
insert into researchers_projects (researcher_id,project_id) values (76,1);
insert into researchers_projects (researcher_id,project_id) values (63,1);
insert into researchers_projects (researcher_id,project_id) values (50,1);
insert into researchers_projects (researcher_id,project_id) values (80,1);
insert into researchers_projects (researcher_id,project_id) values (93,1);
insert into researchers_projects (researcher_id,project_id) values (69,2);
insert into researchers_projects (researcher_id,project_id) values (81,2);
insert into researchers_projects (researcher_id,project_id) values (90,2);
insert into researchers_projects (researcher_id,project_id) values (8,2);
insert into researchers_projects (researcher_id,project_id) values (26,2);
insert into researchers_projects (researcher_id,project_id) values (27,2);
insert into researchers_projects (researcher_id,project_id) values (99,2);
insert into researchers_projects (researcher_id,project_id) values (42,3);
insert into researchers_projects (researcher_id,project_id) values (89,3);
insert into researchers_projects (researcher_id,project_id) values (6,3);
insert into researchers_projects (researcher_id,project_id) values (35,3);
insert into researchers_projects (researcher_id,project_id) values (86,3);
insert into researchers_projects (researcher_id,project_id) values (72,3);
insert into researchers_projects (researcher_id,project_id) values (100,3);
insert into researchers_projects (researcher_id,project_id) values (49,4);
insert into researchers_projects (researcher_id,project_id) values (41,4);
insert into researchers_projects (researcher_id,project_id) values (96,4);
insert into researchers_projects (researcher_id,project_id) values (45,4);
insert into researchers_projects (researcher_id,project_id) values (53,4);
insert into researchers_projects (researcher_id,project_id) values (100,4);
insert into researchers_projects (researcher_id,project_id) values (27,4);
insert into researchers_projects (researcher_id,project_id) values (69,4);
insert into researchers_projects (researcher_id,project_id) values (52,5);
insert into researchers_projects (researcher_id,project_id) values (100,5);
insert into researchers_projects (researcher_id,project_id) values (39,5);
insert into researchers_projects (researcher_id,project_id) values (45,5);
insert into researchers_projects (researcher_id,project_id) values (94,5);
insert into researchers_projects (researcher_id,project_id) values (12,5);
insert into researchers_projects (researcher_id,project_id) values (79,5);
insert into researchers_projects (researcher_id,project_id) values (20,6);
insert into researchers_projects (researcher_id,project_id) values (30,6);
insert into researchers_projects (researcher_id,project_id) values (24,6);
insert into researchers_projects (researcher_id,project_id) values (23,6);
insert into researchers_projects (researcher_id,project_id) values (47,6);
insert into researchers_projects (researcher_id,project_id) values (40,6);
insert into researchers_projects (researcher_id,project_id) values (89,6);
insert into researchers_projects (researcher_id,project_id) values (69,7);
insert into researchers_projects (researcher_id,project_id) values (76,7);
insert into researchers_projects (researcher_id,project_id) values (90,7);
insert into researchers_projects (researcher_id,project_id) values (56,7);
insert into researchers_projects (researcher_id,project_id) values (3,7);
insert into researchers_projects (researcher_id,project_id) values (85,7);
insert into researchers_projects (researcher_id,project_id) values (24,7);
insert into researchers_projects (researcher_id,project_id) values (59,8);
insert into researchers_projects (researcher_id,project_id) values (52,8);
insert into researchers_projects (researcher_id,project_id) values (90,8);
insert into researchers_projects (researcher_id,project_id) values (80,8);
insert into researchers_projects (researcher_id,project_id) values (43,8);
insert into researchers_projects (researcher_id,project_id) values (17,8);
insert into researchers_projects (researcher_id,project_id) values (56,8);
insert into researchers_projects (researcher_id,project_id) values (59,9);
insert into researchers_projects (researcher_id,project_id) values (89,9);
insert into researchers_projects (researcher_id,project_id) values (51,9);
insert into researchers_projects (researcher_id,project_id) values (79,9);
insert into researchers_projects (researcher_id,project_id) values (62,9);
insert into researchers_projects (researcher_id,project_id) values (74,10);
insert into researchers_projects (researcher_id,project_id) values (73,10);
insert into researchers_projects (researcher_id,project_id) values (19,10);
insert into researchers_projects (researcher_id,project_id) values (85,10);
insert into researchers_projects (researcher_id,project_id) values (37,10);
insert into researchers_projects (researcher_id,project_id) values (58,10);
insert into researchers_projects (researcher_id,project_id) values (12,11);
insert into researchers_projects (researcher_id,project_id) values (17,11);
insert into researchers_projects (researcher_id,project_id) values (70,11);
insert into researchers_projects (researcher_id,project_id) values (10,11);
insert into researchers_projects (researcher_id,project_id) values (76,11);
insert into researchers_projects (researcher_id,project_id) values (48,11);
insert into researchers_projects (researcher_id,project_id) values (26,12);
insert into researchers_projects (researcher_id,project_id) values (59,12);
insert into researchers_projects (researcher_id,project_id) values (11,12);
insert into researchers_projects (researcher_id,project_id) values (77,12);
insert into researchers_projects (researcher_id,project_id) values (83,12);
insert into researchers_projects (researcher_id,project_id) values (98,12);
insert into researchers_projects (researcher_id,project_id) values (89,12);
insert into researchers_projects (researcher_id,project_id) values (35,13);
insert into researchers_projects (researcher_id,project_id) values (79,13);
insert into researchers_projects (researcher_id,project_id) values (55,13);
insert into researchers_projects (researcher_id,project_id) values (23,13);
insert into researchers_projects (researcher_id,project_id) values (58,14);
insert into researchers_projects (researcher_id,project_id) values (96,14);
insert into researchers_projects (researcher_id,project_id) values (3,14);
insert into researchers_projects (researcher_id,project_id) values (2,14);
insert into researchers_projects (researcher_id,project_id) values (67,14);
insert into researchers_projects (researcher_id,project_id) values (11,14);
insert into researchers_projects (researcher_id,project_id) values (45,14);
insert into researchers_projects (researcher_id,project_id) values (71,14);
insert into researchers_projects (researcher_id,project_id) values (24,15);
insert into researchers_projects (researcher_id,project_id) values (85,15);
insert into researchers_projects (researcher_id,project_id) values (29,15);
insert into researchers_projects (researcher_id,project_id) values (16,15);
insert into researchers_projects (researcher_id,project_id) values (1,15);
insert into researchers_projects (researcher_id,project_id) values (58,15);
insert into researchers_projects (researcher_id,project_id) values (75,16);
insert into researchers_projects (researcher_id,project_id) values (26,16);
insert into researchers_projects (researcher_id,project_id) values (31,16);
insert into researchers_projects (researcher_id,project_id) values (61,16);
insert into researchers_projects (researcher_id,project_id) values (81,16);
insert into researchers_projects (researcher_id,project_id) values (7,16);
insert into researchers_projects (researcher_id,project_id) values (1,16);
insert into researchers_projects (researcher_id,project_id) values (100,16);
insert into researchers_projects (researcher_id,project_id) values (66,17);
insert into researchers_projects (researcher_id,project_id) values (22,17);
insert into researchers_projects (researcher_id,project_id) values (81,17);
insert into researchers_projects (researcher_id,project_id) values (61,17);
insert into researchers_projects (researcher_id,project_id) values (79,17);
insert into researchers_projects (researcher_id,project_id) values (85,17);
insert into researchers_projects (researcher_id,project_id) values (5,17);
insert into researchers_projects (researcher_id,project_id) values (77,17);
insert into researchers_projects (researcher_id,project_id) values (31,18);
insert into researchers_projects (researcher_id,project_id) values (49,18);
insert into researchers_projects (researcher_id,project_id) values (16,18);
insert into researchers_projects (researcher_id,project_id) values (90,18);
insert into researchers_projects (researcher_id,project_id) values (99,18);
insert into researchers_projects (researcher_id,project_id) values (48,18);
insert into researchers_projects (researcher_id,project_id) values (81,18);
insert into researchers_projects (researcher_id,project_id) values (70,19);
insert into researchers_projects (researcher_id,project_id) values (19,19);
insert into researchers_projects (researcher_id,project_id) values (8,19);
insert into researchers_projects (researcher_id,project_id) values (76,19);
insert into researchers_projects (researcher_id,project_id) values (51,20);
insert into researchers_projects (researcher_id,project_id) values (77,20);
insert into researchers_projects (researcher_id,project_id) values (98,20);
insert into researchers_projects (researcher_id,project_id) values (44,20);
insert into researchers_projects (researcher_id,project_id) values (27,21);
insert into researchers_projects (researcher_id,project_id) values (33,21);
insert into researchers_projects (researcher_id,project_id) values (71,21);
insert into researchers_projects (researcher_id,project_id) values (42,21);
insert into researchers_projects (researcher_id,project_id) values (43,21);
insert into researchers_projects (researcher_id,project_id) values (63,22);
insert into researchers_projects (researcher_id,project_id) values (48,22);
insert into researchers_projects (researcher_id,project_id) values (36,22);
insert into researchers_projects (researcher_id,project_id) values (75,22);
insert into researchers_projects (researcher_id,project_id) values (67,22);
insert into researchers_projects (researcher_id,project_id) values (71,22);
insert into researchers_projects (researcher_id,project_id) values (74,23);
insert into researchers_projects (researcher_id,project_id) values (99,23);
insert into researchers_projects (researcher_id,project_id) values (30,23);
insert into researchers_projects (researcher_id,project_id) values (4,23);
insert into researchers_projects (researcher_id,project_id) values (64,23);
insert into researchers_projects (researcher_id,project_id) values (72,23);
insert into researchers_projects (researcher_id,project_id) values (75,23);
insert into researchers_projects (researcher_id,project_id) values (18,23);
insert into researchers_projects (researcher_id,project_id) values (83,24);
insert into researchers_projects (researcher_id,project_id) values (7,24);
insert into researchers_projects (researcher_id,project_id) values (49,24);
insert into researchers_projects (researcher_id,project_id) values (35,24);
insert into researchers_projects (researcher_id,project_id) values (47,24);
insert into researchers_projects (researcher_id,project_id) values (45,25);
insert into researchers_projects (researcher_id,project_id) values (92,25);
insert into researchers_projects (researcher_id,project_id) values (29,25);
insert into researchers_projects (researcher_id,project_id) values (99,25);
insert into researchers_projects (researcher_id,project_id) values (37,25);
insert into researchers_projects (researcher_id,project_id) values (36,25);
insert into researchers_projects (researcher_id,project_id) values (17,25);
insert into researchers_projects (researcher_id,project_id) values (37,26);
insert into researchers_projects (researcher_id,project_id) values (55,26);
insert into researchers_projects (researcher_id,project_id) values (38,26);
insert into researchers_projects (researcher_id,project_id) values (84,26);
insert into researchers_projects (researcher_id,project_id) values (76,26);
insert into researchers_projects (researcher_id,project_id) values (42,27);
insert into researchers_projects (researcher_id,project_id) values (28,27);
insert into researchers_projects (researcher_id,project_id) values (46,27);
insert into researchers_projects (researcher_id,project_id) values (39,27);
insert into researchers_projects (researcher_id,project_id) values (47,27);
insert into researchers_projects (researcher_id,project_id) values (77,27);
insert into researchers_projects (researcher_id,project_id) values (88,27);
insert into researchers_projects (researcher_id,project_id) values (76,27);
insert into researchers_projects (researcher_id,project_id) values (13,28);
insert into researchers_projects (researcher_id,project_id) values (12,28);
insert into researchers_projects (researcher_id,project_id) values (48,28);
insert into researchers_projects (researcher_id,project_id) values (7,28);
insert into researchers_projects (researcher_id,project_id) values (38,29);
insert into researchers_projects (researcher_id,project_id) values (66,29);
insert into researchers_projects (researcher_id,project_id) values (85,29);
insert into researchers_projects (researcher_id,project_id) values (98,29);
insert into researchers_projects (researcher_id,project_id) values (96,29);
insert into researchers_projects (researcher_id,project_id) values (17,29);
insert into researchers_projects (researcher_id,project_id) values (64,30);
insert into researchers_projects (researcher_id,project_id) values (5,30);
insert into researchers_projects (researcher_id,project_id) values (80,30);
insert into researchers_projects (researcher_id,project_id) values (71,30);
insert into researchers_projects (researcher_id,project_id) values (28,30);
insert into researchers_projects (researcher_id,project_id) values (98,30);
insert into researchers_projects (researcher_id,project_id) values (44,30);
insert into researchers_projects (researcher_id,project_id) values (85,31);
insert into researchers_projects (researcher_id,project_id) values (47,31);
insert into researchers_projects (researcher_id,project_id) values (14,31);
insert into researchers_projects (researcher_id,project_id) values (62,31);
insert into researchers_projects (researcher_id,project_id) values (91,32);
insert into researchers_projects (researcher_id,project_id) values (97,32);
insert into researchers_projects (researcher_id,project_id) values (39,32);
insert into researchers_projects (researcher_id,project_id) values (33,32);
insert into researchers_projects (researcher_id,project_id) values (72,32);
insert into researchers_projects (researcher_id,project_id) values (23,32);
insert into researchers_projects (researcher_id,project_id) values (53,33);
insert into researchers_projects (researcher_id,project_id) values (63,33);
insert into researchers_projects (researcher_id,project_id) values (17,33);
insert into researchers_projects (researcher_id,project_id) values (77,33);
insert into researchers_projects (researcher_id,project_id) values (59,33);
insert into researchers_projects (researcher_id,project_id) values (8,33);
insert into researchers_projects (researcher_id,project_id) values (88,33);
insert into researchers_projects (researcher_id,project_id) values (18,34);
insert into researchers_projects (researcher_id,project_id) values (73,34);
insert into researchers_projects (researcher_id,project_id) values (72,34);
insert into researchers_projects (researcher_id,project_id) values (66,34);
insert into researchers_projects (researcher_id,project_id) values (4,34);
insert into researchers_projects (researcher_id,project_id) values (89,34);
insert into researchers_projects (researcher_id,project_id) values (5,34);
insert into researchers_projects (researcher_id,project_id) values (64,35);
insert into researchers_projects (researcher_id,project_id) values (100,35);
insert into researchers_projects (researcher_id,project_id) values (96,35);
insert into researchers_projects (researcher_id,project_id) values (32,35);
insert into researchers_projects (researcher_id,project_id) values (66,36);
insert into researchers_projects (researcher_id,project_id) values (85,36);
insert into researchers_projects (researcher_id,project_id) values (13,36);
insert into researchers_projects (researcher_id,project_id) values (58,36);
insert into researchers_projects (researcher_id,project_id) values (39,37);
insert into researchers_projects (researcher_id,project_id) values (59,37);
insert into researchers_projects (researcher_id,project_id) values (61,37);
insert into researchers_projects (researcher_id,project_id) values (83,37);
insert into researchers_projects (researcher_id,project_id) values (64,37);
insert into researchers_projects (researcher_id,project_id) values (13,37);
insert into researchers_projects (researcher_id,project_id) values (63,38);
insert into researchers_projects (researcher_id,project_id) values (40,38);
insert into researchers_projects (researcher_id,project_id) values (95,38);
insert into researchers_projects (researcher_id,project_id) values (48,38);
insert into researchers_projects (researcher_id,project_id) values (10,38);
insert into researchers_projects (researcher_id,project_id) values (58,39);
insert into researchers_projects (researcher_id,project_id) values (72,39);
insert into researchers_projects (researcher_id,project_id) values (99,39);
insert into researchers_projects (researcher_id,project_id) values (18,39);
insert into researchers_projects (researcher_id,project_id) values (47,39);
insert into researchers_projects (researcher_id,project_id) values (97,39);
insert into researchers_projects (researcher_id,project_id) values (61,39);
insert into researchers_projects (researcher_id,project_id) values (55,40);
insert into researchers_projects (researcher_id,project_id) values (9,40);
insert into researchers_projects (researcher_id,project_id) values (56,40);
insert into researchers_projects (researcher_id,project_id) values (100,40);
insert into researchers_projects (researcher_id,project_id) values (64,41);
insert into researchers_projects (researcher_id,project_id) values (59,41);
insert into researchers_projects (researcher_id,project_id) values (14,41);
insert into researchers_projects (researcher_id,project_id) values (88,41);
insert into researchers_projects (researcher_id,project_id) values (2,41);
insert into researchers_projects (researcher_id,project_id) values (17,41);
insert into researchers_projects (researcher_id,project_id) values (87,41);
insert into researchers_projects (researcher_id,project_id) values (53,41);
insert into researchers_projects (researcher_id,project_id) values (99,42);
insert into researchers_projects (researcher_id,project_id) values (16,42);
insert into researchers_projects (researcher_id,project_id) values (70,42);
insert into researchers_projects (researcher_id,project_id) values (24,42);
insert into researchers_projects (researcher_id,project_id) values (50,42);
insert into researchers_projects (researcher_id,project_id) values (42,42);
insert into researchers_projects (researcher_id,project_id) values (62,43);
insert into researchers_projects (researcher_id,project_id) values (55,43);
insert into researchers_projects (researcher_id,project_id) values (39,43);
insert into researchers_projects (researcher_id,project_id) values (98,43);
insert into researchers_projects (researcher_id,project_id) values (26,43);
insert into researchers_projects (researcher_id,project_id) values (90,43);
insert into researchers_projects (researcher_id,project_id) values (17,43);
insert into researchers_projects (researcher_id,project_id) values (81,44);
insert into researchers_projects (researcher_id,project_id) values (30,44);
insert into researchers_projects (researcher_id,project_id) values (86,44);
insert into researchers_projects (researcher_id,project_id) values (24,44);
insert into researchers_projects (researcher_id,project_id) values (45,44);
insert into researchers_projects (researcher_id,project_id) values (79,44);
insert into researchers_projects (researcher_id,project_id) values (83,44);
insert into researchers_projects (researcher_id,project_id) values (21,44);
insert into researchers_projects (researcher_id,project_id) values (91,45);
insert into researchers_projects (researcher_id,project_id) values (26,45);
insert into researchers_projects (researcher_id,project_id) values (39,45);
insert into researchers_projects (researcher_id,project_id) values (95,45);
insert into researchers_projects (researcher_id,project_id) values (19,45);
insert into researchers_projects (researcher_id,project_id) values (35,45);
insert into researchers_projects (researcher_id,project_id) values (7,45);
insert into researchers_projects (researcher_id,project_id) values (54,45);
insert into researchers_projects (researcher_id,project_id) values (13,46);
insert into researchers_projects (researcher_id,project_id) values (16,46);
insert into researchers_projects (researcher_id,project_id) values (41,46);
insert into researchers_projects (researcher_id,project_id) values (68,46);
insert into researchers_projects (researcher_id,project_id) values (11,46);
insert into researchers_projects (researcher_id,project_id) values (77,47);
insert into researchers_projects (researcher_id,project_id) values (69,47);
insert into researchers_projects (researcher_id,project_id) values (49,47);
insert into researchers_projects (researcher_id,project_id) values (60,47);
insert into researchers_projects (researcher_id,project_id) values (88,47);
insert into researchers_projects (researcher_id,project_id) values (40,47);
insert into researchers_projects (researcher_id,project_id) values (31,47);
insert into researchers_projects (researcher_id,project_id) values (62,48);
insert into researchers_projects (researcher_id,project_id) values (92,48);
insert into researchers_projects (researcher_id,project_id) values (88,48);
insert into researchers_projects (researcher_id,project_id) values (1,48);
insert into researchers_projects (researcher_id,project_id) values (31,48);
insert into researchers_projects (researcher_id,project_id) values (15,48);
insert into researchers_projects (researcher_id,project_id) values (48,48);
insert into researchers_projects (researcher_id,project_id) values (37,48);
insert into researchers_projects (researcher_id,project_id) values (16,49);
insert into researchers_projects (researcher_id,project_id) values (82,49);
insert into researchers_projects (researcher_id,project_id) values (35,49);
insert into researchers_projects (researcher_id,project_id) values (89,49);
insert into researchers_projects (researcher_id,project_id) values (73,49);
insert into researchers_projects (researcher_id,project_id) values (71,50);
insert into researchers_projects (researcher_id,project_id) values (30,50);
insert into researchers_projects (researcher_id,project_id) values (2,50);
insert into researchers_projects (researcher_id,project_id) values (100,50);
